{{- range $secret, $secret_config := .Values.secrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secret }}
spec:
  refreshInterval: {{ $.Values.global.refreshInterval}}
  secretStoreRef:
    name: {{ $.Values.global.secretStore }}
    kind: {{ $.Values.global.secretStoreKind }}
  data:
    {{- range $k8sKey, $awsKey := $secret_config.keys }}
    - secretKey: {{ $k8sKey }}
      remoteRef:
        key: {{ $secret_config.awsSecret}}
        property: {{ $awsKey }}
    {{- end }}
---
{{- end }}