{{- $global := .Values.global }}
{{- range $cluster, $config := .Values.clusters }}
{{- $connect_name := (printf "%s-%s" (include "kafka-connect.name" $) $cluster) }}
{{- if $config.ingress -}}
{{- if $config.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $connect_name }}-api
  annotations:
    {{- range $key, $value := $config.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if $config.ingress.ingressClass -}}
  ingressClassName: {{ $config.ingress.ingressClass }}
  {{- end }}
  rules:
  {{- range $host := $config.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - backend:
              service:
                name: {{ $connect_name }}-connect-api
                port:
                  number: 8083
            path: /
            pathType: Prefix
  {{- end }}
  tls:
    - hosts:
      {{- range $host := $config.ingress.hosts }}
        - {{ $host }}
      {{- end }}
      secretName: {{ $connect_name }}-tls
---
{{- end }}
{{- end }}
{{- end }}