{{- if and .Values.license.key (not .Values.license.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-backup-enterprise.fullname" . }}-license
  labels:
    {{- include "kafka-backup-enterprise.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.license.existingSecretKey | default "license-b64" }}: {{ .Values.license.key | quote }}
{{- end }}
