{{- if and .Values.credentials.inline (not .Values.credentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-backup-enterprise.fullname" . }}-credentials
  labels:
    {{- include "kafka-backup-enterprise.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.credentials.inline }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
